version: '3.8'
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-vector
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rag_db10
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: D:\HUST\2024.1\Sinno_RAG_pipepline\demo\data