# Generated by Django 3.2.16 on 2024-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
