# Generated by Django 3.2.16 on 2024-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241103_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='plotImages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
