# Generated by Django 3.2.16 on 2025-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241103_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='plotImages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
