# Generated by Django 3.2.16 on 2024-12-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_uploadedfile_plotimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
