# Generated by Django 3.2.16 on 2024-12-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20241228_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploadName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
